//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_account_type
    {
        public int acc_type_id { get; set; }
        public string acc_type { get; set; }
        public bool status { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
