//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DailyPaymentEntities : DbContext
    {
        public DailyPaymentEntities()
            : base("name=DailyPaymentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_product> tbl_product { get; set; }
        public virtual DbSet<vw_select_product> vw_select_product { get; set; }
        public virtual DbSet<tbl_supplier> tbl_supplier { get; set; }
        public virtual DbSet<tbl_stock> tbl_stock { get; set; }
        public virtual DbSet<vw_select_stock> vw_select_stock { get; set; }
    }
}
