//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_daily_rate
    {
        public int rate_id { get; set; }
        public decimal b_sale_out { get; set; }
        public decimal b_buy_in { get; set; }
        public decimal s_sale_out { get; set; }
        public decimal s_buy_in { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
