//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int inv_id { get; set; }
        public string inv_code { get; set; }
        public System.DateTime inv_date { get; set; }
        public System.DateTime entry_date { get; set; }
    }
}
