//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profit_type
    {
        public int pro_type_id { get; set; }
        public string pro_type { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
