//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice_detail
    {
        public int inv_detail_id { get; set; }
        public int inv_id { get; set; }
        public int pro_id { get; set; }
        public int spl_id { get; set; }
        public int cur_id { get; set; }
        public int qty { get; set; }
        public decimal unit_price { get; set; }
    }
}
