//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier
    {
        public int spl_id { get; set; }
        public string spl_name { get; set; }
        public string place { get; set; }
        public System.DateTime entry_date { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
    }
}
