//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Payment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_select_stock
    {
        public int st_id { get; set; }
        public int pro_id { get; set; }
        public int cat_id { get; set; }
        public string pro_name { get; set; }
        public string category { get; set; }
        public int spl_id { get; set; }
        public string spl_name { get; set; }
        public string place { get; set; }
        public int qty { get; set; }
        public string unit_price { get; set; }
        public string total_price { get; set; }
        public string currency { get; set; }
        public string sign { get; set; }
        public System.DateTime st_date { get; set; }
    }
}
